# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
