# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160326_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AddField(
            model_name='myuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', '--')], default='NS', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set([('email',)]),
        ),
    ]
