# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qac', '0004_remove_comment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoted_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
