# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qac', '0008_auto_20160412_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='answers_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='comments_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='questions_downvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
